### ISSUE TITLE
Window round corner not working

### ISSUE THREAD

**Issue by DineshDevaraj** [nwjs/nw.js#1165]
I'm using the following style to make the window corners round. The corners are getting round but the background is white instead of being transparent.

``` css
html{
    overflow:hidden;
    background:transparent;    
    -webkit-border-radius:5px; 
}
```

Development Environment
Operating System : Windows 7 Enterprise
Node-Webkit Version : 0.7.5
