### ISSUE TITLE
Fonts rendering differently to Chrome on Windows 7

### ISSUE THREAD

**Issue by JonathanRowley** [nwjs/nw.js#1728]
Using the following code:

```css
h2 {
  color: #f37419;
  font-weight: bold;
  font-size: 1.5em;
  font: 2em/1.8 ITCAvantGardeGothicProBook, Arial, Helvetica, Verdana, sans-serif;
}
```
Left is node-webkit, right is native Chrome:
![image](https://f.cloud.github.com/assets/1837201/2511140/14eb5a58-b413-11e3-86fa-c17895cdf948.png)
