### ISSUE TITLE
0.11.1 - net::ERR_CACHE_READ_FAILURE - chromium 38 issue 424599

### ISSUE THREAD

**Issue by clintwood** [nwjs/nw.js#2661]
Although [this chromium 38 issue](https://code.google.com/p/chromium/issues/detail?id=424599) is said to be _"this bug is not about actual load failures, but about misleading error reports..."_ I am finding I have the same result as [this posters image in the same issue thread](https://code.google.com/p/chromium/issues/detail?id=424599#c47).

I'm getting the same results as this poster (blanked out fonts).  I am using a SVG font via `@font-face` in my main style CSS file as follows:
```css
@font-face {
  font-family: 'e-qpr-icons';
  src: url('fonts/e-qpr-icons.svg?89183612#e-qpr-icons') format('svg');
  font-weight: normal;
  font-style: normal;
}
```
So what I believe is happening is that the `net::ERR_CACHE_READ_FAILURE` is somehow causing the `src: url(...)` statements NOT to be loaded and therefore breaking the font.

This is a real issue for me... According to the same chromium 38 issue above this is fixed in chromium 40...

This might be related to #2654 (not enough information to validate)
