### ISSUE TITLE
Enhancement Request: Add '-apple-system' support for font-family.

### ISSUE THREAD

**Issue by mnorton-ffs** [nwjs/nw.js#3773]
In OS X 10.11 El Capitan, Apple has deprecated the idea of specifically targetable system UI fonts, replacing them with an '-apple-system' declaration that causes the app to display using San Francisco.

It would be great if nw.js could support this flag so that we can write apps that continue to feel at home on OS X.
##

**Comment by asifshirazi** [comment]
+1

**Comment by ghostoy** [comment]
I googled a QA on stackoverflow: http://stackoverflow.com/questions/32660748/how-to-use-apples-new-san-francisco-font-on-a-webpage.
You can try if following css works:
```css
body {
    font-family: -apple-system, BlinkMacSystemFont, sans-serif;
}
```
