### ISSUE TITLE
styling scrollbar with css doesn't work

### ISSUE THREAD

**Issue by leiwan5** [nwjs/nw.js#414]
``` css
::-webkit-scrollbar {
    background: blue;
}
::-webkit-scrollbar-thumb {
    background: red;
}
::-webkit-scrollbar-thumb:hover {
    background: yellow;
}
```

This code snippet works in chrome browser, but doesn't in node-webkit. 
The red "thumb" doesn't show up.
I don't know if it's an issue of cef.
