### ISSUE TITLE
Iframe is not getting 100% height and width. is it normal or BUG?

### ISSUE THREAD

**Issue by shamun** [nwjs/nw.js#4229]
How can i set the iFrame on full-screen mode? its failing
```
<!DOCTYPE html>
<html>
<head>
<style>
iframe {
border: 0px;
width:100%;
height:100%;
}
</style>
</head>

<body style="margin:0px;padding:0px;">
<iframe src="https://career.bpost.be/nl" width="100%" height="100%"></iframe>

<script>
var gui = require('nw.gui');
var sys = require('sys');
var exec = require('child_process').exec;
var win = gui.Window.get();
var child;
var run_void;
var input = gui.App.argv;

var set_timer = null;
window.onload = function() {
    win.show();
  set_timer = global.setTimeout(function() {
	alert("Closing the window now.");
	gui.App.quit();
  }, 5000);
};

</script>
</body>
</html>
```

**Comment by offshore** [comment]
That's completely not related to nw.
The `iframe` tag uses `display: inline` as default model, so there are some related overheads.
Use this css, it will solve your case (includes some additional enforcements):
```css
html, body {
    margin: 0;
    padding: 0;
}
iframe {
    display: block;
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    margin: 0;
    padding: 0;
    border: 0;
}
```
