### ISSUE TITLE
Feature request:backdrop-filter support transparent window

### ISSUE THREAD

**Issue by lazyseastar** [nwjs/nw.js#4769]
If backdrop-filter had effects on transparent window background would very cool.For example,make it possible to use the below code to blur the pixels under transparent window("chromium-args": "--enable-experimental-web-platform-features").
```css
html {
    background-color: rgba(255, 255, 255, 0.6);
    backdrop-filter: blur(10px);
}
```
