### ISSUE TITLE
No rounded corners (or shadows) on transparent windows

### ISSUE THREAD

**Issue by anesuc** [nwjs/nw.js#7144]
NWJS Version : 0.35.4
Operating System : Linux with window managers that support blur on window (tested on Kubuntu 16.04, Ubuntu 16.04 etc)

### Expected behavior

Applying border-radius to html element should apply a boarder radius on the window. There is also no shadows, which can be understandable, an option to add them would be great. But the end result is a square flat window, especially with blur behind it.

### Actual behavior

As stated above no rounded corners and no way to do this, even applying a radius to the html tag. The end result is flat sharp corners which does not look good.

Here is a screenshot example:
https://image.prntscr.com/image/3Oob8LgeTbW_eDuojY-TPg.png

https://image.prntscr.com/image/Y9s58yKGSI_Tb72ttxkfig.png

### How to reproduce

Set the appropriate transparent variable in package.json, make the body and html transparent and if you are on a Linux distribution that allows blur you can add it (or MacOS I guess) behind and then try to get the corners to be rounded

**Comment by panther7** [comment]
Images are forbidden 403

**Comment by anesuc** [comment]
Try again, they are working fine on my side. I even tried incognito mode and on a different device on a different network haha

**Comment by AndikaTanpaH** [comment]
**i cant open your image**
for this i was use this css on html

```css
html, body{width: 100%;height: 100%;}
body{background-color:rgba(0,0,0,0); /*this make your body transparent*/}
```

and you can add border-radius on element below the body

i'm use ubuntu 16.04

**Comment by anesuc** [comment]
Interesting. Do these links work?
https://prntscr.com/oxpo5n
https://prntscr.com/oxpo5j

@AndikaTanpaH the problem isn't making it transparent, it's making the transparent windows have rounded corners or even shadows if possible. Although I really would wnt to have shadows if it's at all possible, I would be more than happy if we can have rounded corners

**Comment by AndikaTanpaH** [comment]
@anesuc  it's was you want to achieve? look it https://prnt.sc/ozgpel

**Old Way**
```css
.body{position:relative;}
.outerbox{position: absolute;bottom:0;top:0;left:0;right:0;margin: 5px;}
```
**Modern Way**
```css
body{padding: 5px;}
body, .outerbox{box-sizing: border-box;}
.outerbox{width: 100%;height: 100%;}
```
Old way need margin on child, Modern way need padding on parent. This space for shadow, just a my cent a shadow cannot show on outer window apps. So we must make some space in window apps.

### Full Code Modern Way:
```css
html, body{padding: 0;margin: 0;width: 100%;height: 100%;}
body{background-color:rgba(0,0,0,0);overflow: hidden;padding: 5px;}
body, .outerbox{box-sizing: border-box;}

.outerbox{
  width: 100%;height: 100%;
  background: rgba(20,20,20,0.7);border-radius: 10px;box-shadow: 0 0 5px #222;
  overflow: hidden;
}
```
```html
<body>
  <div class="outerbox"><!-- Your content inside here--></div>
</body>
```
