### ISSUE TITLE
Override the OS light/dark theme

### ISSUE THREAD

**Issue by TheJaredWilcurt** [nwjs/nw.js#8046]
This request is to add a JavaScript API that would override the `prefers-color-scheme` value in the browser.

## Motivation

* It is not uncommon to default your application to a light or dark mode based on the OS, but also allow users to change this based on a setting in the application
* If your application has a third party site embedded in an iframe or webview, it will not have access to your application settings, and therefor won't match the theme

## Prior art:

* https://www.electronjs.org/docs/latest/api/native-theme#nativethemethemesource

## API Proposal:

Setting must be `'dark'`, `'light'` or `'system'` (the default).

In `package.json` or when passed in to `nw.Window.open`

```js
"window": {
  "native-theme": "dark"
}
```

In app:

```js
const win = nw.Window.get();
win.setNativeTheme('dark');
```

This could work similar to [win.setShadow](https://nwjs.readthedocs.io/en/latest/References/Window/#winsetshadowshadow-mac).

## Desired Outcome

After setting this value in NW.js, if any HTML, CSS, or JavaScript attempt to detect the value will receive the value set in NW.js:

**HTML:**

```html
<link rel="stylesheet" href="/dark.css" media="(prefers-color-scheme: dark)" />
<link rel="stylesheet" href="/light.css" media="(prefers-color-scheme: light)" />
<picture>
  <source srcset="western.webp" media="(prefers-color-scheme: dark)" />
  <source srcset="eastern.webp" media="(prefers-color-scheme: light)" />
  <img src="eastern.webp" />
</picture>
```

**CSS:**

```css
@media (prefers-color-scheme: dark) {
  body { background: #000 }
}
@media (prefers-color-scheme: light) {
  body { background: #FFF }
}

**JS:**

```js
if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
  console.log('dark');
}
if (window.matchMedia('(prefers-color-scheme: light)').matches) {
  console.log('light');
}
if (window.matchMedia('(not (prefers-color-scheme: light))').matches) {
  console.log('dark');
}
if (window.matchMedia('(not (prefers-color-scheme: dark))').matches) {
  console.log('light');
}
```

## Update Event

If the OS changes it's theme, JS can listen for the event and run code. This should be left as-is. If the NW.js app dev wants to ignore this change and re-run their `win.setNativeTheme('dark');` code again, they can do that.

* * *

This feature was requested by `panther7` in the Gitter chatroom.
